### ISSUE TITLE
Blender 2.9.3 Error when converting to mesh

### ISSUE THREAD

**Issue by melriksdesign** [Kinthamen/blender_bspheres#1]
Using Blender 2.9.3, When I click convert to a mesh, I get an error 
\bSpheres.py line 68, in execute bpy.ops.object.modifier_apply(apply_as="data', modifier="Mirror")
\ops.py like 132, in_call_ ret = _op_call(self.idname_py(), none, kw)
TypeError Converting py args to operator properties: keywork "apply_as" unrecognized.

**Comment by PapaTemporal** [comment]
Looking into it now.

**Comment by PapaTemporal** [comment]
Ok. updated. Please try this release. https://github.com/Kinthamen/blender_bspheres/releases/tag/v1-0-0

**Comment by melriksdesign** [comment]
Thanks!  Works.
